### PR TITLE
Some hacks to make stuff kinda work + debug stuff

### PR DESCRIPTION
**Pull request by vgrichina**

### CODE REVIEW

**Comment by emaG3m** [comment]
Are there plans to get this merged? I see some good stuff in here that addresses a few of our issues, but it seems like things need to get cleaned up

**Comment by vgrichina** [comment]
@emaG3m this for sure wasn't planned to merge as is.

> I see some good stuff in here that addresses a few of our issues

May you be a bit more specific here? I can clean up specific things, but also feel free to just copy stuff / merge in other branch.

**Comment by emaG3m** [comment]
> May you be a bit more specific here?

Looks like I was mostly referring to logs translation. At this point it'd be a huge merge conflict though, so no worries!

**Comment by vgrichina** [comment]
@emaG3m np, closing this

**Review by Tomek00177 — COMMENTED** [review]
Orłowski

**Review by Tomek00177 — COMMENTED** [review]
Gggh

**Pull request closed without merging**
